### ISSUE TITLE
 systematic failure (IllegalStateException) importing a directory from the file system

### ISSUE THREAD

**Issue by alessio-santacroce** [pmonks/alfresco-bulk-import#44] opened 2015-09-18 11:21 UTC
Hi there,

I am experiencing a systematic failure trying to import a directory from the file system.
The import fails with the following message:

--------------------------------------------------------------------------------
2015-09-14 01:57:16,142  INFO  [bulkimport.impl.LoggingBulkImportCompletionHandler] [BulkImport-Scanner] BULKIMPORT: In place bulk import completed **(Failed)** in 11m 48s 131.246ms.
	Batches:		**103 imported of 130 submitted (0.145 / sec)**
	Nodes:			10300 (14.545 / sec)
	Bytes:			0 (0.000 / sec)
	Versions:		0
	Metadata properties:	72080
	Files:			0 in-place, 0 streamed, 0 skipped
	Out-of-order batches:	**65409**

--------------------------------------------------------------------------------

The problem seems related to the high number od out-of-order batches, the following exception is printed in the log files before the bulk import failure message:

--------------------------------------------------------------------------------
2015-09-14 01:57:13,032  ERROR [bulkimport.impl.Scanner] [BulkImport-Scanner] BULKIMPORT: Bulk import from 'Default' failed.
 java.lang.IllegalStateException: Attempt to register more than 65535 parties for java.util.concurrent.Phaser@173710b6[phase = 0 parties = 65535 arrived = 65508]
	at java.util.concurrent.Phaser.doRegister(Phaser.java:429)
	at java.util.concurrent.Phaser.register(Phaser.java:579)
	at org.alfresco.extension.bulkimport.impl.Scanner.submitBatch(Scanner.java:358)
	at org.alfresco.extension.bulkimport.impl.Scanner.submitCurrentBatch(Scanner.java:331)
	at org.alfresco.extension.bulkimport.impl.Scanner.submit(Scanner.java:300) 

--------------------------------------------------------------------------------
	
Reading the log files, we noticed many WARN lines saying that a node cannot be created in Alfresco because a parent folder is missing and for that reason the whole batch is re-submitted. It seems when too many submitted batches, the threshold of 65535 parties is reached and the IllegalStateException is raised.
We don't know why the parent folder was not created in advance, there are no message in the log about an error creating a folder.

The root folder we are trying to import has:
 - 17,331 folders (it's a complex folder structure)
 - 206,526 files (including the metadata files)
 - about 91 GB of data
 
We have tried to import it with the following configurations:
 - 5 threads, batch of 50
 - 5 threads, batch of 1
 - 1 threads, batch of 50
 
 
Many thanks in advance,
Alessio

**Comment by pmonks** [comment] 2015-09-19 07:24
G'day Alessio,

What happens when you leave the thread and batch size configuration at the defaults?

Cheers,
Peter

Apologes for speling & gramar erorrs - sent from mobil deivce

**Comment by alessio-santacroce** [comment] 2015-09-23 14:05
Hi Peter,

I apologize for the late reply. We tried with many different configurations.
This issue was a blocker for us and eventually we managed to make it work changing the code.

In our experience, this is an issue due to multithreading; even if the creation of the folder in Alfresco repository is started with the correct order, in our case (17,000 folders), are not generated with the same order and many "create folder" jobs have to be re-queued, possibly more than once, until the exception is raised and the import terminates with a failure.

We modified the "BulkImporterImpl.java" and "Scanner.java" to instantiate and run the Scanner twice, the  first time in a single thread to generate the folder structure only, the second time to import only the files in multithread. Using this approach, no batch is out-of-order; all the batches succeeded and, in addition, we have noticed that the whole process seems faster than before, at least in our scenario.
We can share the code with you.

Regards,
Alessio

**Comment by pmonks** [comment] 2015-09-24 01:04
G'day Alessio,

Which version of the tool are you using?

v2.0 of the tool already loads folders first, files second, and only uses (at most) 2 threads during the folder phase (regardless of the number of configured threads).  As a result there should not be a high number of retries due to out-of-order batches.  Indeed I've never witnessed any in the unit tests (albeit they only load around 160,000 files spread across several thousand folders).

Are you able to provide your folder structure to me, perhaps via personal email (pmonks@gmail.com), so that I can try to reproduce the issue?

Cheers,
Peter

Apologes for speling & gramar erorrs - sent from mobil deivce

**Comment by pmonks** [comment] 2015-10-02 02:18
G'day Alessio,

I created a test case for this here
<https://github.com/pmonks/alfresco-bulk-import/blob/master/test/data/SinglePassTests/FolderStructureTests/make-large-folder-structure.clj>
[1] and was able to reproduce what you're seeing.  This is actually caused
by two semi-related issues:

   1. Issue #45 <https://github.com/pmonks/alfresco-bulk-import/issues/45>
   [2] - phasers need to be tiered
   2. Issue #46 <https://github.com/pmonks/alfresco-bulk-import/issues/46>
   [3] - large directory structures result in many OoO batches

I've scheduled fixes for both issues for v2.0.1 - in fact the fix for issue
#45
<https://github.com/pmonks/alfresco-bulk-import/commit/82e205d2acabac99811ed2e806c50890c2a4dfc9>
[4]
is already committed, which allows such imports to succeed (albeit with
many OoO retries).  I'll aim to get the new version out in the coming weeks.

Thanks again for your report.

Cheers,
Peter

[1]
https://github.com/pmonks/alfresco-bulk-import/blob/master/test/data/SinglePassTests/FolderStructureTests/make-large-folder-structure.clj
[2] https://github.com/pmonks/alfresco-bulk-import/issues/45
[3] https://github.com/pmonks/alfresco-bulk-import/issues/46
[4]
https://github.com/pmonks/alfresco-bulk-import/commit/82e205d2acabac99811ed2e806c50890c2a4dfc9

**Comment by pmonks** [comment] 2015-10-02 02:20
Issue #45 duplicates this one, but it has more information so I'll mark this one as the duplicate.

**Closed by pmonks** 2015-10-02 02:20 UTC
Labels: duplicate
