### ISSUE TITLE
OutOfOrderBatchException being thrown 2.10 and Alfresco 5.0.2

### ISSUE THREAD

**Issue by colindstephenson** [pmonks/alfresco-bulk-import#61] opened 2016-08-24 14:46 UTC
### Steps to Reproduce:

Create a content model with custom folders and custom types.
Create a setup of import data which sets the folders to the custom folder types and the documents to the custom document types.
### Expected Result:

The successful ingestion of the data.  V1.34 was able to do this (I assume this was due to lack of OutOfOrderBatch testing?)
### Actual Result:

See stack trace below.  Triggered by

``` java
//####TODO: I THINK THIS WILL FAIL IN THE PRESENCE OF CUSTOM NAMESPACES / PARENT ASSOC QNAMES!!!!
fileInfo = serviceRegistry.getFileFolderService().resolveNamePath(target, itemParentPathElements, false);
```

in [BulkImporterImpl.java:323](https://github.com/pmonks/alfresco-bulk-import/blob/master/amp/src/main/java/org/alfresco/extension/bulkimport/impl/BatchImporterImpl.java#L323)
### Environment:

Cent OS 6.6
Alfresco Enterprise 5.0.2
Bulk Importer 2.10
### Description of Problem:

```
org.alfresco.extension.bulkimport.impl.OutOfOrderBatchException
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.getParent(BatchImporterImpl.java:334)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.findOrCreateNode(BatchImporterImpl.java:252)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.importItem(BatchImporterImpl.java:200)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.importBatchImpl(BatchImporterImpl.java:184)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.access$200(BatchImporterImpl.java:69)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl$2.execute(BatchImporterImpl.java:161)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.importBatchInTxn(BatchImporterImpl.java:152)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.access$000(BatchImporterImpl.java:69)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl$1.doWork(BatchImporterImpl.java:130)
    at org.alfresco.repo.security.authentication.AuthenticationUtil.runAs(AuthenticationUtil.java:548)
    at org.alfresco.extension.bulkimport.impl.BatchImporterImpl.importBatch(BatchImporterImpl.java:124)
    at org.alfresco.extension.bulkimport.impl.Scanner.submitCurrentBatch(Scanner.java:333)
    at org.alfresco.extension.bulkimport.impl.Scanner.submit(Scanner.java:294)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:223)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:245)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:245)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:245)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:245)
    at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanFiles(FilesystemBulkImportSource.java:172)
    at org.alfresco.extension.bulkimport.impl.Scanner.run(Scanner.java:184)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by colindstephenson** [comment] 2016-08-24 14:47
Being able to disable OutOfOrder checking through a configuration option would be handy.

**Comment by pmonks** [comment] 2016-08-24 18:33
@colindstephenson it's not possible to disable OutOfOrder checking - Alfresco itself will fail if an attempt is made to import a child is imported before its parent.  All the tool does is check for that condition and throw a more meaningful exception.

**Comment by colindstephenson** [comment] 2016-08-24 19:00
@pmonks understood, it just is causing problems, even after refactoring custom folders to be cm:folders with aspects.  There is something else, either in the folder aspects or custom types which is also posing issues.  I will see if I can share the content models with you if you are interested in sharing the pain.

**Comment by pmonks** [comment] 2016-08-24 20:20
@colindstephenson did you try a fresh import?  If you'd previously imported folders as custom types or with custom child assocs they will prevent *new* imports from working as well.

**Comment by pmonks** [comment] 2016-08-24 20:22
Keep in mind that the [tests](https://github.com/pmonks/alfresco-bulk-import/tree/master/test/data/SinglePassTests) (specifically the `FolderStructure` and `FileFolderVolume` tests) are pretty exhaustive, so I'm pretty confident that vanilla `cm:folder`s do indeed work.  ;-)

**Comment by colindstephenson** [comment] 2016-09-04 14:18
ok, so in further testing, when a cm:name property is added to the folder metadata this falls flat on its arse.  the resolveNamePath fails as i think it is looking for the on disk name rather than the name supplied through metadata.

**Comment by colindstephenson** [comment] 2016-09-04 15:14
ok, so I don't think the custom types for folders is an issue.  Once I removed cm:name from folder metadata, I can create custom folders with custom aspects, etc.  Looking at the resolveNamePath() code in FileFolderService, as long as the association is that of ASSOC_CONTAINS then customtypes should work.

**Comment by pmonks** [comment] 2016-11-14 23:29
Duplicate of #62.

**Closed** 2016-11-15 18:36 UTC
Labels: duplicate
